export const zh: Record<string, string> = {
  'Output truncated; retrying one smaller step':
    '输出达到上限，正在尝试一个更小的步骤（仅重试一次）',
  'Correcting model tool arguments': '正在修正模型工具参数',

  'Output allowance includes reasoning tokens. High reasoning may need a larger limit; the provider must support the value.':
    '输出额度也包含推理 tokens。高推理等级可能需要更高额度，数值须在模型支持范围内。',

  'Close details': '关闭详情',
  Context: '上下文',
  Files: '文件',
  'Settings & usage': '设置与用量',
  'Team strategy': '协作策略',
  'Single agent': '关闭委派',
  'Automatic delegation': '自动委派',
  'Prefer collaboration': '优先协作',
  'Windows AppContainer': 'Windows 原生文件隔离',
  'Native Python interpreter': '原生适配器 Python 路径',
  'Native network policy': '原生网络策略',
  'Strict offline · fail closed': '严格离线 · 预检失败拒绝执行',
  'File isolation · network not guaranteed blocked': '文件隔离 · 不保证阻断网络',
  'Review child changes': '审阅子任务改动',
  Conflict: '冲突',
  'Configure your models and choose how tools may run.': '配置模型连接，选择工具的执行方式。',
  Protocol: '协议',
  'Base URL': '接口地址',
  'Reasoning protocol': '推理参数协议',
  'Context window': '上下文容量',
  'Maximum output tokens': '最大输出 token',
  'Request timeout (seconds)': '单次请求超时（秒）',
  'Vision input supported': '支持图片输入',
  'Supported reasoning levels · confirm with the provider': '可选推理等级 · 以服务商实际支持为准',
  'Optional pricing · USD per million tokens': '可选价格 · 每百万 token 的美元单价',
  'Usage comes from API responses. These rates produce an estimate, not a provider bill.':
    '用量来自 API 响应。价格计算为估算，并非服务商最终账单。',
  Default: '默认连接',
  'Command backend': '命令执行后端',
  'Host process · explicit approval': '宿主进程 · 明确审批',
  'Docker · no network': 'Docker · 禁用网络',
  'Docker image': 'Docker 镜像',
  'Parallel model runs': '并行模型请求数',
  'Maximum delegation depth': '最大委派深度',
  'Maximum children per run tree': '每棵任务树的子任务上限',
  'Context compaction threshold': '上下文压缩触发比例',
  'Embedding connection': '向量模型连接',
  'Optional. Indexing sends document chunks to this endpoint. Lexical search works without it; vector search is exact, not ANN.':
    '可选配置。建立向量索引会将文档分块发送至此接口。不配置仍可全文检索；当前向量检索为精确检索，不是 ANN。',
  Model: '模型',
  'API key': 'API 密钥',
  'MCP servers': 'MCP 服务',
  'Add server': '添加服务',
  'Enabling a server authorizes its configured host process to start. Trust the executable first. Individual tool calls still require approval.':
    '启用服务即授权启动所配置的宿主进程，请先确认程序可信。每次工具调用仍需独立审批。',
  'Arguments · one per line': '参数 · 每行一个',
  Enabled: '已启用',
  'Working…': '处理中…',
  'Skill folder': '技能文件夹',
  'Choose a scope': '选择范围',
  'Paste a document': '粘贴文档',
  'Document name': '文档名称',
  'Document text…': '文档正文…',
  'Test retrieval…': '测试检索…',
  'User · all chats': '用户记忆 · 所有对话',
  'Preference or verified fact…': '偏好或已验证的事实…',
  'Index vectors': '建立向量索引',
  Active: '已生效',
  'Needs confirmation': '待确认',
  Deactivate: '停用',
  Confirm: '确认',
  'Explore a project': '探索项目',
  'Understand code, plan a change': '理解代码，规划修改',
  'Work with documents': '处理文档',
  'Find answers grounded in sources': '基于原始资料查找答案',
  'Start with a question': '从问题开始',
  'Think through something together': '一起分析、梳理想法',
  'YOUR LOCAL WORKSPACE': '你的本地工作空间',
  'A LITTLE SPACE FOR BIG IDEAS': '让想法在这里成为现实',
  'YOUR CONTEXT': '知识与偏好',
  PREFERENCES: '偏好设置',
  Local: '本机',
  'No project attached': '未绑定项目',
  'Create a chat to configure its tools.': '创建对话后，可在这里配置工具。',
  Input: '输入',
  Output: '输出',
  'Cache hits': '缓存命中',
  'Cost estimate': '费用估算',
  'Record inspected outcome': '记录已核实的结果',
  'Interrupted output': '已中断的输出',
  You: '你',
  AgentDemo: 'AgentDemo',
  Thinking: '思考中',
  'Saved · leave unchanged to keep it': '已保存 · 不修改则保留',
  'Enter key': '输入密钥',
  Unknown: '未知',
  'Saved · unchanged to retain': '已保存 · 不修改则保留',
};
